default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: doHiring_development

test:
  <<: *default
  database: doHiring_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
