default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: dohiring_development

test:
  <<: *default
  database: dohiring_test

production:
  <<: *default
  database: dohiring_production
  username: dohiring
  password: <%= ENV['DOHIRING_DATABASE_PASSWORD'] %>